# name: Sync to Hugging Face hub
# on:
#   push:
#     branches: [master]

#   # to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   sync-to-hub:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Add remote 
#         env:
#           HF: ${{ secrets.HUGGINGFACE }}
#         run: git remote add space https://vaishali-r99:$HF@huggingface.co/spaces/vaishali-r99/demo
#       - name: Push to hub
#         env:
#           HF: ${{ secrets.HUGGINGFACE }}
#         run: git push --force https://vaishali-r99:$HF@huggingface.co/spaces/vaishali-r99/demo master

# name: Sync to Hugging Face hub (Python 3.9)

# on:
#   push:
#     branches: [master]

#   # to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   sync-to-hub:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         python-version: [3.9]  # Set Python version to 3.9

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       # Set up Python 3.9 environment
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       # Install dependencies (TensorFlow 2.11 and Keras 2.11)
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install tensorflow==2.11.0 keras==2.11.0 transformers==4.31.0 gradio

#       # Add Hugging Face remote repository
#       - name: Add remote 
#         env:
#           HF: ${{ secrets.HUGGINGFACE }}
#         run: git remote add space https://vaishali-r99:$HF@huggingface.co/spaces/vaishali-r99/demo

#       # Push to Hugging Face hub
#       - name: Push to hub
#         env:
#           HF: ${{ secrets.HUGGINGFACE }}
#         run: git push --force https://vaishali-r99:$HF@huggingface.co/spaces/vaishali-r99/demo master


# Branch issue
name: Sync to Hugging Face hub

on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Uninstall existing Keras
        run: |
          pip uninstall -y keras

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-cpu==2.16.1
          pip install tf-keras==2.16.0 --no-dependencies
          pip install keras==2.11.0 transformers==4.31.0 gradio

      # Rename 'master' branch to 'main' for Hugging Face if necessary
      - name: Rename Branch
        run: |
          git branch -m master main || true
          git fetch origin
          git branch -u origin/main main || true

      - name: Add remote 
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git remote add space https://vaishali-r99:$HF@huggingface.co/spaces/vaishali-r99/demo

      - name: Push to hub
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git push --force https://vaishali-r99:$HF@huggingface.co/spaces/vaishali-r99/demo main
